Esse arquivo √© um Docker Compose (vers√£o 3.8).
Ele define quais servi√ßos existem, como s√£o constru√≠dos, como se comunicam e quais vari√°veis de ambiente usam.

üëâ Pense nele como o ‚Äúmapa de implanta√ß√£o‚Äù do sistema.

version: '3.8'

x-airflow-common:
  &airflow-common
  build:
    context: ./ETL
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
    - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
    - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__LOGGING_LEVEL=INFO
    - AIRFLOW_CONN_POSTGRES_MASTER=${AIRFLOW_CONN_POSTGRES_MASTER}
    - APIS=${APIS}
    - BEARER_TOKEN=${BEARER_TOKEN} 
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    - PYTHONPATH=/opt/airflow/modules
    - AIRFLOW__CORE__DEFAULT_TIMEZONE=America/Sao_Paulo
    - AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE=America/Sao_Paulo
  volumes:
    - ./ETL/dags:/opt/airflow/dags            # DAGs vis√≠veis pelo scheduler e webserver
    - ./ETL/logs:/opt/airflow/logs            # Logs persistentes
    - ./ETL/plugins:/opt/airflow/plugins      # Plugins e hooks customizados
    - ./ETL/modules:/opt/airflow/modules      # (opcional) C√≥digo auxiliar fora da pasta DAG
    - ./ETL/config:/opt/airflow/config 
    - ./common_settings:/opt/airflow/common_settings 
  depends_on:
    - postgres
  networks:
    - main

services:
  postgres:
    build:
      context: ./database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${VPN_IP}:${POSTGRES_PORT}:5432"
    
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/backup:/backup
    networks:
      - main

  postgrest:
    image: postgrest/postgrest:latest
    environment:
      - PGRST_DB_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      - PGRST_DB_ANON_ROLE=app_user
      - PGRST_DB_SCHEMA=public
      - PGRST_SERVER_HOST=0.0.0.0
      - PGRST_SERVER_PORT=3000
    ports:
      - "${VPN_IP}:${POSTGREST_PORT}:3000"  # PostgREST estar√° acess√≠vel na porta 3000
    networks:
      - main
    depends_on:
      - postgres 

  airflow-init:
    << : *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate && \
        airflow users create \
          --role Admin \
          --username airflow \
          --password airflow \
          --email airflow@airflow.com \
          --firstname airflow \
          --lastname airflow
    restart: on-failure
    networks:
      - main


  airflow-webserver:
    << : *airflow-common
    command: airflow webserver
    ports:
      - "${VPN_IP}:${AIRFLOW_PORT}:8080"
    container_name: airflow_webserver
    restart: always
    networks:
      - main
  

  airflow-scheduler:
    << : *airflow-common
    command: airflow scheduler
    container_name: airflow_scheduler
    networks:
      - main


  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - dashboard
      - airflow-webserver
      - postgrest
    networks:
      - main



  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "${VPN_IP}:${VUE_PORT}:5000"
    volumes:
      - ./common_settings:/app/public
      - ./dashboard:/app
      - ./dashboard/certs:/app/certs
      - /app/node_modules
    command: npm run ${RUN_MODE}
    environment:
      - NODE_ENV=development
      - PORT=5000
      - POSTGREST_URL=http://${VPN_IP}:${POSTGREST_PORT}
    networks:
      - main
    depends_on:
      - postgres 
      - postgrest


      
networks:
  main:
    driver: bridge

